image:
    file: .gitpod.Dockerfile
ports:
- port: 8000
  onOpen: open-browser
- port: 8001
  onOpen: open-browser
- port: 8002
  onOpen: open-browser
- port: 8080
  onOpen: open-browser
tasks:
  - init: cd api && composer install
    command: $(which php) -S 0.0.0.0:8000 -t ./api/public .htrouter.php
  - init: cd client && npm install
    command: quasar dev
